-- One passkey per person, not per ticket.
--
-- A credential is identified by (rpId, user.id), so a fresh user handle per ticket left
-- the device listing one entry per event. Deriving the handle from the verified email
-- gives a person a single credential that every one of their tickets rides on - and a
-- second device simply adds a credential to the same identity rather than a whole new
-- one per ticket.
CREATE TABLE holder (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    -- Stable, derived from the email: re-registering on the same device replaces the
    -- entry instead of adding another.
    user_handle VARCHAR(128) NOT NULL UNIQUE,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE holder_credential (
    credential_id   VARCHAR(1400) PRIMARY KEY,
    holder_id       BIGINT        NOT NULL REFERENCES holder(id) ON DELETE CASCADE,
    public_key      TEXT          NOT NULL,
    signature_count BIGINT        NOT NULL DEFAULT 0,
    aaguid          VARCHAR(64),
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    last_used_at    TIMESTAMP
);
CREATE INDEX idx_holder_credential_holder ON holder_credential(holder_id);

-- The ticket now points at the person rather than owning a credential of its own.
ALTER TABLE ticket ADD COLUMN holder_id BIGINT REFERENCES holder(id);
CREATE INDEX idx_ticket_holder ON ticket(holder_id);

DROP TABLE ticket_passkey;
