-- A protected link becomes a container, the way an event session is for tickets:
-- the link holds the document and its policy, and each recipient is issued their own
-- address under it. Until now the link itself was the address, so one link could only
-- ever reach one person.
CREATE TABLE link_recipient (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id    BIGINT      NOT NULL REFERENCES protected_link(id) ON DELETE CASCADE,
    short_code VARCHAR(32) NOT NULL UNIQUE,
    label      VARCHAR(255),
    status     VARCHAR(20) NOT NULL DEFAULT 'ISSUED',
    view_count INT         NOT NULL DEFAULT 0,
    created_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    claimed_at TIMESTAMP
);
CREATE INDEX idx_link_recipient_link ON link_recipient(link_id);

-- The passkey binds to the person, not to the document.
CREATE TABLE recipient_passkey (
    recipient_id    BIGINT        PRIMARY KEY REFERENCES link_recipient(id) ON DELETE CASCADE,
    credential_id   VARCHAR(1400) NOT NULL UNIQUE,
    user_handle     VARCHAR(128)  NOT NULL UNIQUE,
    public_key      TEXT          NOT NULL,
    signature_count BIGINT        NOT NULL DEFAULT 0,
    receiver_name   VARCHAR(100)  NOT NULL,
    claimed_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

-- Every existing link keeps working: its address becomes its first recipient, carrying
-- the passkey and the view count that address already had.
INSERT INTO link_recipient (link_id, short_code, label, status, view_count, created_at)
SELECT l.id, l.short_code, l.recipient_names,
       CASE WHEN EXISTS (SELECT 1 FROM link_passkey p WHERE p.link_id = l.id) THEN 'BOUND' ELSE 'ISSUED' END,
       COALESCE(l.view_count, 0), l.created_at
  FROM protected_link l;

INSERT INTO recipient_passkey (recipient_id, credential_id, user_handle, public_key,
                               signature_count, receiver_name, claimed_at)
SELECT r.id, p.credential_id, p.user_handle, p.public_key,
       p.signature_count, p.receiver_name, p.claimed_at
  FROM link_passkey p
  JOIN link_recipient r ON r.link_id = p.link_id;

DROP TABLE link_passkey;

-- Views are attributed to the recipient who opened the document.
ALTER TABLE link_view ADD COLUMN recipient_id BIGINT REFERENCES link_recipient(id) ON DELETE SET NULL;
UPDATE link_view SET recipient_id = (
    SELECT MIN(r.id) FROM link_recipient r WHERE r.link_id = link_view.link_id);
