-- Portable DDL: runs on H2 (dev/test) and PostgreSQL/Supabase (production).
-- GENERATED BY DEFAULT AS IDENTITY is SQL-standard and supported by both.
CREATE TABLE protected_link (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code      VARCHAR(32)   NOT NULL UNIQUE,
    owner_sub       VARCHAR(255),
    original_url    VARCHAR(2048) NOT NULL,
    title           VARCHAR(255),
    password_hash   VARCHAR(255),
    expires_at      TIMESTAMP,
    recipient_names VARCHAR(500),
    max_views       INT           DEFAULT 0,
    view_count      INT           DEFAULT 0,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE link_view (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id     BIGINT       NOT NULL REFERENCES protected_link(id) ON DELETE CASCADE,
    viewer_name VARCHAR(100),
    viewed_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE link_passkey (
    link_id         BIGINT        PRIMARY KEY REFERENCES protected_link(id) ON DELETE CASCADE,
    credential_id   VARCHAR(1400) NOT NULL UNIQUE,
    user_handle     VARCHAR(128)  NOT NULL UNIQUE,
    public_key      TEXT          NOT NULL,
    signature_count BIGINT        NOT NULL DEFAULT 0,
    receiver_name   VARCHAR(100)  NOT NULL,
    claimed_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_protected_link_owner ON protected_link(owner_sub);
CREATE INDEX idx_link_view_link ON link_view(link_id);
