-- Crowding the organiser defines, rather than a shape read off the busiest place.
--
-- Relative crowding says "this door is the worst one right now", which is true even when
-- the building is empty and useless when every place is full. A place with a capacity is
-- measured against it; a place without one keeps the relative reading, so an event that
-- never fills the numbers in still shows something.
CREATE TABLE zone_capacity (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT      NOT NULL REFERENCES event_session(id) ON DELETE CASCADE,
    zone       VARCHAR(80) NOT NULL,
    capacity   INT         NOT NULL,
    UNIQUE (session_id, zone)
);

-- Where the two lines sit, as a percentage of capacity. The defaults are the thresholds
-- the panel has been using all along, so an event that says nothing reads as before.
ALTER TABLE event_session ADD COLUMN crowd_busy_percent   INT NOT NULL DEFAULT 75;
ALTER TABLE event_session ADD COLUMN crowd_steady_percent INT NOT NULL DEFAULT 40;
