-- What an issued ticket carries, as the organiser defines it.
--
-- Seats and tiers were the only two things a ticket could say about itself, and both
-- were hard-wired. An organiser who needs a table number, a workshop track or a meal
-- choice had nowhere to put it. A field is a name plus the values it offers; a field
-- with no values takes free text.
--
-- Seats keep their own column and their unique index, because "one seat, one ticket" is
-- a rule the database enforces. Everything else lives on the ticket as JSON: it is read
-- and written whole, never queried by key.
CREATE TABLE ticket_field (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT      NOT NULL REFERENCES event_session(id) ON DELETE CASCADE,
    label      VARCHAR(40) NOT NULL,
    kind       VARCHAR(10) NOT NULL DEFAULT 'CUSTOM',
    values_csv TEXT,
    position   INT         NOT NULL DEFAULT 0,
    UNIQUE (session_id, label)
);
CREATE INDEX idx_ticket_field_session ON ticket_field(session_id);

ALTER TABLE ticket ADD COLUMN attributes TEXT;

-- The seats and tiers already configured become the first two fields, so nothing an
-- organiser set up disappears behind the new screen.
INSERT INTO ticket_field (session_id, label, kind, values_csv, position)
SELECT id, '좌석', 'SEAT', seats, 0 FROM event_session
WHERE seats IS NOT NULL AND seats <> '';
INSERT INTO ticket_field (session_id, label, kind, values_csv, position)
SELECT id, '등급', 'TIER', tiers, 1 FROM event_session
WHERE tiers IS NOT NULL AND tiers <> '';
