-- Content the account writes here, rather than somewhere else it has to link to.
--
-- A protected link has always pointed outward: paste a URL, protect it. For work that
-- exists only to be shared - a set of works, a short brief - that meant publishing it
-- somewhere first and protecting the copy. The link can now point at a document held
-- here instead, which is never served except through the recipient's own passkey.
CREATE TABLE link_content (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_sub  VARCHAR(255) NOT NULL,
    title      VARCHAR(200) NOT NULL,
    kind       VARCHAR(20)  NOT NULL DEFAULT 'EXHIBITION',
    body       TEXT         NOT NULL,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_link_content_owner ON link_content(owner_sub);

-- One destination or the other: a URL somewhere else, or a document here.
ALTER TABLE protected_link ADD COLUMN content_id BIGINT REFERENCES link_content(id);
ALTER TABLE protected_link ALTER COLUMN original_url DROP NOT NULL;
