-- Searchable artwork rows are kept beside the authored JSON document. A delivery
-- copies selected rows into its own content snapshot, so later edits do not change
-- material that a recipient has already received.
CREATE TABLE artwork (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_sub         VARCHAR(255) NOT NULL,
    source_content_id BIGINT NOT NULL REFERENCES link_content(id) ON DELETE CASCADE,
    position          INTEGER NOT NULL,
    image_url         TEXT,
    artist            VARCHAR(300),
    title             VARCHAR(500) NOT NULL,
    year_text         VARCHAR(100),
    medium            TEXT,
    width_text        VARCHAR(100),
    height_text       VARCHAR(100),
    depth_text        VARCHAR(100),
    unit_text         VARCHAR(20),
    description       TEXT,
    price_text        VARCHAR(300),
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_content_id, position)
);

CREATE INDEX idx_artwork_owner ON artwork(owner_sub);
CREATE INDEX idx_artwork_source_content ON artwork(source_content_id);
