-- Coupons, by booth.
--
-- A ticket is what gets somebody through the door; a coupon is what they can pick up
-- once inside, and it belongs to a booth rather than to the event as a whole. Each row
-- is one offer for one person, because that is the thing that gets redeemed: "one
-- welcome drink for seat A-1", not "a drink offer that exists somewhere".
--
-- The title and the detail are copied onto the row rather than pointed at a template.
-- What somebody was promised must keep saying what it said when they were given it,
-- even after the organiser rewrites the offer for the next batch.
CREATE TABLE booth (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT       NOT NULL REFERENCES event_session(id) ON DELETE CASCADE,
    name       VARCHAR(80)  NOT NULL,
    note       VARCHAR(300),
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_booth_session ON booth(session_id);

CREATE TABLE coupon (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT       NOT NULL REFERENCES event_session(id) ON DELETE CASCADE,
    booth_id      BIGINT       NOT NULL REFERENCES booth(id) ON DELETE CASCADE,
    ticket_id     BIGINT       NOT NULL REFERENCES ticket(id) ON DELETE CASCADE,
    title         VARCHAR(80)  NOT NULL,
    detail        TEXT,
    -- ISSUED until it is handed over, then REDEEMED. VOID is the organiser taking it
    -- back, which keeps the row rather than pretending it was never given.
    status        VARCHAR(16)  NOT NULL DEFAULT 'ISSUED',
    issued_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    redeemed_at   TIMESTAMP,
    redeemed_gate VARCHAR(32)
);
CREATE INDEX idx_coupon_ticket ON coupon(ticket_id, status);
CREATE INDEX idx_coupon_booth ON coupon(booth_id, status);
-- The same offer twice to the same person is a mistake, not a second drink.
CREATE UNIQUE INDEX uq_coupon_offer ON coupon(ticket_id, booth_id, title);

-- What a terminal is for. An admission gate moves people through a door; a booth
-- terminal hands things over, and reads the same code to do it.
ALTER TABLE gate ADD COLUMN role     VARCHAR(16) NOT NULL DEFAULT 'ADMISSION';
ALTER TABLE gate ADD COLUMN booth_id BIGINT REFERENCES booth(id) ON DELETE SET NULL;
