-- What each booth is allowed to give.
--
-- Until now a coupon's name was typed at the moment it was given, so "웰컴 드링크" and
-- "웰컴드링크" were two offers and nothing stopped a stand being credited with something
-- it does not have. An offer is now defined on the booth first, and giving a coupon
-- means picking one of that booth's offers that is still switched on.
--
-- The coupon row still keeps its own copy of the title and detail. What somebody was
-- given must keep saying what it said, even after the offer is switched off.
CREATE TABLE coupon_offer (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT       NOT NULL REFERENCES event_session(id) ON DELETE CASCADE,
    booth_id   BIGINT       NOT NULL REFERENCES booth(id) ON DELETE CASCADE,
    title      VARCHAR(80)  NOT NULL,
    detail     TEXT,
    -- Off means no more of it can be given. Coupons already given are unaffected.
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uq_coupon_offer_title ON coupon_offer(booth_id, title);

-- Every offer already handed out becomes a defined one, with the wording it was last
-- given under.
INSERT INTO coupon_offer (session_id, booth_id, title, detail)
SELECT c.session_id, c.booth_id, c.title,
       (SELECT c2.detail FROM coupon c2
         WHERE c2.booth_id = c.booth_id AND c2.title = c.title
         ORDER BY c2.id DESC LIMIT 1)
  FROM coupon c
 GROUP BY c.session_id, c.booth_id, c.title;

ALTER TABLE coupon ADD COLUMN offer_id BIGINT REFERENCES coupon_offer(id) ON DELETE SET NULL;
UPDATE coupon SET offer_id = (
    SELECT o.id FROM coupon_offer o WHERE o.booth_id = coupon.booth_id AND o.title = coupon.title);
CREATE INDEX idx_coupon_offer ON coupon(offer_id);
-- The console pages through a session's coupons; this is the order it reads them in.
CREATE INDEX idx_coupon_session ON coupon(session_id, booth_id, id);
