-- Phase 0-1: ticket URL model, passkey binding, rotating-code presentation,
-- and the append-only admission ledger with re-entry presence state.

CREATE TABLE event_session (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     VARCHAR(200) NOT NULL,
    venue                    VARCHAR(200),
    starts_at                TIMESTAMP    NOT NULL,
    gate_opens_at            TIMESTAMP,
    -- Re-entry / exit policy (design section 11). Server-configurable per session.
    reentry_mode             VARCHAR(16)  NOT NULL DEFAULT 'LIMITED',
    reentry_max              INT          NOT NULL DEFAULT 3,
    reentry_grace_minutes    INT          NOT NULL DEFAULT 45,
    reentry_cooldown_seconds INT          NOT NULL DEFAULT 60,
    exit_scan_required       BOOLEAN      NOT NULL DEFAULT TRUE,
    unmatched_exit           VARCHAR(16)  NOT NULL DEFAULT 'LENIENT',
    auto_exit_after_minutes  INT          NOT NULL DEFAULT 240,
    created_at               TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ticket (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       BIGINT       NOT NULL REFERENCES event_session(id) ON DELETE CASCADE,
    -- Opaque reference carried in the QR payload. Never the personal token.
    ticket_ref       VARCHAR(32)  NOT NULL UNIQUE,
    -- Only the HMAC of the personal token is stored, so a database read does not
    -- hand out live claim URLs.
    token_hmac       VARCHAR(64)  NOT NULL UNIQUE,
    seat             VARCHAR(32),
    tier             VARCHAR(32),
    status           VARCHAR(24)  NOT NULL DEFAULT 'ISSUED',
    issued_to_email  VARCHAR(255) NOT NULL,
    holder_email     VARCHAR(255),
    bound_at         TIMESTAMP,
    claim_expires_at TIMESTAMP,
    transfer_count   INT          NOT NULL DEFAULT 0,
    reissue_count    INT          NOT NULL DEFAULT 0,
    created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ticket_session ON ticket(session_id);

-- One passkey per ticket URL: the primary key enforces the invariant.
CREATE TABLE ticket_passkey (
    ticket_id       BIGINT        PRIMARY KEY REFERENCES ticket(id) ON DELETE CASCADE,
    credential_id   VARCHAR(1400) NOT NULL UNIQUE,
    user_handle     VARCHAR(128)  NOT NULL UNIQUE,
    public_key      TEXT          NOT NULL,
    signature_count BIGINT        NOT NULL DEFAULT 0,
    aaguid          VARCHAR(64),
    holder_email    VARCHAR(255)  NOT NULL,
    claimed_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE email_otp (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    purpose     VARCHAR(32)  NOT NULL,
    code_hash   VARCHAR(64)  NOT NULL,
    expires_at  TIMESTAMP    NOT NULL,
    attempts    INT          NOT NULL DEFAULT 0,
    consumed_at TIMESTAMP,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_email_otp_lookup ON email_otp(email, purpose, created_at);

-- Issued only after a passkey user-verification ceremony. Carries the short-lived
-- secret the phone uses to sign rotating codes, and dies on first successful scan.
CREATE TABLE presentation_session (
    id           VARCHAR(32) PRIMARY KEY,
    ticket_id    BIGINT      NOT NULL REFERENCES ticket(id) ON DELETE CASCADE,
    direction    VARCHAR(4)  NOT NULL,
    secret       VARCHAR(64) NOT NULL,
    uv           BOOLEAN     NOT NULL,
    last_counter BIGINT      NOT NULL DEFAULT -1,
    issued_at    TIMESTAMP   NOT NULL,
    expires_at   TIMESTAMP   NOT NULL,
    consumed_at  TIMESTAMP
);
CREATE INDEX idx_presentation_ticket ON presentation_session(ticket_id, issued_at);

-- Single-use rotating-code nonces. The primary key is the replay defence.
CREATE TABLE qr_nonce (
    nonce   VARCHAR(32) PRIMARY KEY,
    used_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- Direction comes from the terminal's identity, never from the QR payload.
CREATE TABLE gate (
    id           VARCHAR(32)  PRIMARY KEY,
    session_id   BIGINT       NOT NULL REFERENCES event_session(id) ON DELETE CASCADE,
    label        VARCHAR(100),
    zone         VARCHAR(32),
    direction    VARCHAR(16)  NOT NULL,
    token_hmac   VARCHAR(64)  NOT NULL,
    last_seen_at TIMESTAMP
);

-- Derived current state. Row-locked on every transition so two gates cannot
-- admit the same ticket concurrently.
CREATE TABLE ticket_presence (
    ticket_id     BIGINT      PRIMARY KEY REFERENCES ticket(id) ON DELETE CASCADE,
    session_id    BIGINT      NOT NULL,
    state         VARCHAR(8)  NOT NULL DEFAULT 'OUTSIDE',
    entry_count   INT         NOT NULL DEFAULT 0,
    reentry_count INT         NOT NULL DEFAULT 0,
    inside_since  TIMESTAMP,
    last_exit_at  TIMESTAMP,
    last_event_at TIMESTAMP,
    last_gate_id  VARCHAR(32),
    updated_at    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- Append-only ledger. Corrections are added as new rows, never updates.
CREATE TABLE admission_event (
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id              BIGINT       REFERENCES ticket(id) ON DELETE CASCADE,
    session_id             BIGINT,
    direction              VARCHAR(4),
    gate_id                VARCHAR(32),
    method                 VARCHAR(16)  NOT NULL,
    result                 VARCHAR(24)  NOT NULL,
    reason                 VARCHAR(200),
    presentation_session_id VARCHAR(32),
    occurred_at            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_admission_ticket ON admission_event(ticket_id, occurred_at);
CREATE INDEX idx_admission_session ON admission_event(session_id, occurred_at);
