-- Phase 2: transfer. A ticket moves to a new holder by rotating its personal URL,
-- so the sender's link dies at the moment the recipient claims.

ALTER TABLE event_session ADD COLUMN transfer_max INT NOT NULL DEFAULT 2;
ALTER TABLE event_session ADD COLUMN transfer_closes_minutes_before INT NOT NULL DEFAULT 120;
ALTER TABLE event_session ADD COLUMN transfer_after_first_entry BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE ticket_transfer (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id      BIGINT       NOT NULL REFERENCES ticket(id) ON DELETE CASCADE,
    from_email     VARCHAR(255) NOT NULL,
    to_email       VARCHAR(255) NOT NULL,
    -- Keyed hash of the recipient's claim token; the ticket keeps the sender's token
    -- until the claim completes, which is what leaves the sender able to cancel.
    to_token_hmac  VARCHAR(64)  NOT NULL UNIQUE,
    status         VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    policy_snapshot VARCHAR(500),
    requested_ip   VARCHAR(64),
    requested_ua   VARCHAR(255),
    expires_at     TIMESTAMP    NOT NULL,
    accepted_at    TIMESTAMP,
    closed_at      TIMESTAMP,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_transfer_ticket ON ticket_transfer(ticket_id, status);
