-- Phase 3: face recognition as an alternative entry track.
-- Templates are bound to the ticket, not to a person: they are created with the ticket
-- and destroyed with it, which keeps the retention story simple and the blast radius small.

ALTER TABLE event_session ADD COLUMN face_required BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE event_session ADD COLUMN reentry_requires_face BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE event_session ADD COLUMN face_liveness VARCHAR(32) NOT NULL DEFAULT 'PASSIVE';
ALTER TABLE event_session ADD COLUMN face_challenge_on VARCHAR(16) NOT NULL DEFAULT 'LOW_SCORE_ONLY';
ALTER TABLE event_session ADD COLUMN face_retention_days INT NOT NULL DEFAULT 7;

-- Sensitive personal data under the Personal Information Protection Act needs its own
-- consent record, kept separately from the ticket so withdrawal is a first-class action.
CREATE TABLE face_consent (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id       BIGINT       NOT NULL REFERENCES ticket(id) ON DELETE CASCADE,
    email           VARCHAR(255) NOT NULL,
    consent_version VARCHAR(32)  NOT NULL,
    purposes        VARCHAR(300) NOT NULL,
    retain_until    TIMESTAMP    NOT NULL,
    consented_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    withdrawn_at    TIMESTAMP
);
CREATE INDEX idx_face_consent_ticket ON face_consent(ticket_id);

-- No raw image column exists, by design. Only the encrypted feature vector is kept.
CREATE TABLE face_template (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id     BIGINT      NOT NULL UNIQUE REFERENCES ticket(id) ON DELETE CASCADE,
    session_id    BIGINT      NOT NULL,
    algo_version  VARCHAR(32) NOT NULL,
    dimensions    INT         NOT NULL,
    quality       DOUBLE PRECISION NOT NULL,
    vector        TEXT        NOT NULL,
    enrolled_at   TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    revoked_at    TIMESTAMP,
    purge_after   TIMESTAMP   NOT NULL
);
CREATE INDEX idx_face_template_session ON face_template(session_id, revoked_at);

-- Match attempts, kept for dispute handling. Scores and outcomes only; never frames.
CREATE TABLE face_attempt (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT      NOT NULL,
    ticket_id    BIGINT,
    gate_id      VARCHAR(32),
    stage        VARCHAR(24) NOT NULL,
    result       VARCHAR(24) NOT NULL,
    score        DOUBLE PRECISION,
    runner_up    DOUBLE PRECISION,
    liveness     DOUBLE PRECISION,
    reason       VARCHAR(200),
    occurred_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_face_attempt_session ON face_attempt(session_id, occurred_at);
