-- Local administrator sign-in, so the console works without a Google tenancy.
-- Passwords are stored only as BCrypt hashes, and repeated failures lock the account
-- rather than leaving it open to guessing.
CREATE TABLE admin_account (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    display_name   VARCHAR(100),
    failed_logins  INT          NOT NULL DEFAULT 0,
    locked_until   TIMESTAMP,
    last_login_at  TIMESTAMP,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
